### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rkern** [cvxgrp/a2dr#3]
The project's metadata declares this project as Apache-licensed, but many of the individual files have headers declaring that file to be GPLed. Can you clarify which license is the correct one?

This looks a lot like the project started off as GPLed but then switched to the Apache license like CVXPY did. If so, can you confirm that all contributors agreed to the license change?

Thank you very much.

**Comment by junziz** [comment]
Hi Robert,

Yes you are right! The project started off as GPLed but we then switched to Apache and so we confirm that the project is Apache-licensed now. Thanks a lot for pointing this out and we will edit the individual files to be consistent with the Apache license shortly!

**Comment by rkern** [comment]
Thank you very much!

**Comment by junziz** [comment]
Our pleasure!
